# Generated by Django 2.2.1 on 2020-10-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo', models.ImageField(upload_to='img')),
            ],
        ),
    ]
