# Generated by Django 2.2.1 on 2020-10-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_goodstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shelf_life', models.CharField(max_length=128)),
                ('production_date', models.DateField()),
                ('desc', models.CharField(max_length=128)),
                ('images', models.ImageField(upload_to='img')),
                ('goodstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.GoodsType')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Store')),
            ],
        ),
    ]
