# Generated by Django 2.2.1 on 2020-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=models.TextField(default='商品详情'),
        ),
    ]
