# Generated by Django 2.2.1 on 2020-10-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_goods_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
