# Generated by Django 2.2.1 on 2020-10-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=128)),
                ('goods_img', models.CharField(max_length=128)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_num', models.IntegerField(default=20)),
                ('store_id', models.IntegerField()),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.BuyerUser')),
            ],
        ),
    ]
