# Generated by Django 2.2.1 on 2020-10-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=64)),
                ('detail_address', models.CharField(max_length=128)),
                ('postcode', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.BuyerUser')),
            ],
        ),
    ]
