# Generated by Django 2.2.1 on 2020-10-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_numbering', models.CharField(max_length=128)),
                ('order_date', models.DateTimeField()),
                ('order_address', models.CharField(max_length=128)),
                ('order_total', models.CharField(max_length=32)),
                ('order_status', models.BooleanField(default=False)),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.BuyerUser')),
            ],
        ),
    ]
