# Generated by Django 2.2.1 on 2020-10-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=128)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('goods_img', models.CharField(max_length=128)),
                ('goods_num', models.IntegerField()),
                ('goods_total', models.CharField(max_length=32)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Orders')),
            ],
        ),
    ]
