# Generated by Django 2.2.1 on 2020-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_ordersdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=64)),
                ('ver_code', models.CharField(max_length=32)),
                ('times', models.DateTimeField()),
            ],
        ),
    ]
